//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherComputerRetrievalConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeacherComputerRetrievalConsoleApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string DashLine {
            get {
                return ResourceManager.GetString("DashLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE DISTANCE:.
        /// </summary>
        internal static string EnterDistance {
            get {
                return ResourceManager.GetString("EnterDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE ENDING ACADEMY:.
        /// </summary>
        internal static string EnterEndingAcademy {
            get {
                return ResourceManager.GetString("EnterEndingAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE EXACT NUMBER OF STOPS:.
        /// </summary>
        internal static string EnterExactNumberOfStops {
            get {
                return ResourceManager.GetString("EnterExactNumberOfStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE MAXIMUM NUMBER OF STOPS:.
        /// </summary>
        internal static string EnterMaxNumberOfStops {
            get {
                return ResourceManager.GetString("EnterMaxNumberOfStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER A ROUTE TO GET THE DISTANCE:.
        /// </summary>
        internal static string EnterRouteToGetDistance {
            get {
                return ResourceManager.GetString("EnterRouteToGetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE STARTING ACADEMY:.
        /// </summary>
        internal static string EnterStartingAcademy {
            get {
                return ResourceManager.GetString("EnterStartingAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER A VALID NUMBER.
        /// </summary>
        internal static string EnterValidNumber {
            get {
                return ResourceManager.GetString("EnterValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND TOTAL DISTANCE OF A INPUT ROUTE.
        /// </summary>
        internal static string FindDistance {
            get {
                return ResourceManager.GetString("FindDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND NUMBER OF POSSIBLE ROUTES BETWEEN TWO ACADEMIES WITH EXACT &apos;N&apos; NUMBER OF STOP(S).
        /// </summary>
        internal static string FindNumberOfRoutesWithExactStops {
            get {
                return ResourceManager.GetString("FindNumberOfRoutesWithExactStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND NUMBER OF POSSIBLE ROUTES BETWEEN TWO ACADEMIES WITH MAXIMUM OF &apos;N&apos; NUMBER OF STOP(S).
        /// </summary>
        internal static string FindNumberOfRoutesWithMaxStops {
            get {
                return ResourceManager.GetString("FindNumberOfRoutesWithMaxStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND ALL POSSIBLE ROUTES BETWEEN TWO ACADEMIES HAVING DISTANCE LESS THAN &apos;N&apos;.
        /// </summary>
        internal static string FindPossibleRoutesHavingDistance {
            get {
                return ResourceManager.GetString("FindPossibleRoutesHavingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND SHORTEST ROUTE BETWEEN TWO ACADEMIES.
        /// </summary>
        internal static string FindShortestRoute {
            get {
                return ResourceManager.GetString("FindShortestRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT LIST OF ROUTES AND DISTANCE BETWEEN THEM:.
        /// </summary>
        internal static string InputRoutesList {
            get {
                return ResourceManager.GetString("InputRoutesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER THE LIST OF ROUTES COMMA(&apos;,&apos;) SEPERATED....
        /// </summary>
        internal static string InputRoutesText {
            get {
                return ResourceManager.GetString("InputRoutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID ACTION! PLEASE TRY AGAIN..
        /// </summary>
        internal static string InvalidActionTryAgain {
            get {
                return ResourceManager.GetString("InvalidActionTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID ROUTE. .
        /// </summary>
        internal static string InvalidRoute {
            get {
                return ResourceManager.GetString("InvalidRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID ROUTE STRUCTURE..
        /// </summary>
        internal static string InvalidRouteStructure {
            get {
                return ResourceManager.GetString("InvalidRouteStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELOW ARE THE LIST OF POSSIBLE ROUTES:.
        /// </summary>
        internal static string ListOfPossibleRoutesText {
            get {
                return ResourceManager.GetString("ListOfPossibleRoutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO SUCH ROUTE.
        /// </summary>
        internal static string NoSuchRoute {
            get {
                return ResourceManager.GetString("NoSuchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF POSSIBLE ROUTES FROM {0} TO {1} WITH A DISTANCE OF LESS THAN {2} : {3}.
        /// </summary>
        internal static string NumberOfPossibleRoutes {
            get {
                return ResourceManager.GetString("NumberOfPossibleRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSSIBLE ROUTES BETWEEN {0} &amp; {1} : {2}.
        /// </summary>
        internal static string PossibleRoutesBW {
            get {
                return ResourceManager.GetString("PossibleRoutesBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FROM BELOW ACTIONS:.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHORTEST DISTANCE BETWEEN {0} &amp; {1} : {2}.
        /// </summary>
        internal static string ShortestDistanceRoute {
            get {
                return ResourceManager.GetString("ShortestDistanceRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL DISTANCE BETWEEN THIS ROUTE IS:.
        /// </summary>
        internal static string TotalDistanceBWRoutes {
            get {
                return ResourceManager.GetString("TotalDistanceBWRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO TEACHER COMPUTER RETRIEVAL PROGRAM.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR INPUT:.
        /// </summary>
        internal static string YourInput {
            get {
                return ResourceManager.GetString("YourInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WANT TO PROCEED WITH ANOTHER QUESTION? YES/NO:.
        /// </summary>
        internal static string YouWantToProceed {
            get {
                return ResourceManager.GetString("YouWantToProceed", resourceCulture);
            }
        }
    }
}
